### ISSUE TITLE
变量名不规范，请修改。

### ISSUE THREAD

**Issue by yudequan** [Cheer201704/Homework#3]
变量名不规范，请修改。

**Comment by yudequan** [comment]
`public class Admin
{
	String name = "admin";

	String password = "admin";

	// 授权方法
	public boolean authorize(String arg0, String arg1)
	{
		return name.equals(arg0) && password.equals(arg1) ? true : false;
	}

	// 修改密码
	public boolean modifyPassword(String arg)
	{
		password = arg;

		// TODO do check password
		return true;
	}
}`

**Comment by wanghanyangks** [comment]
`package Work0418;

public class User {
	String cardType;
	int integral;
	public void exchange(){
		if("金卡".equals(cardType)&&integral>1000){
			System.out.println("恭喜您获得500积分");
		}else if("普通卡".equals(cardType)&&integral>5000){
			System.out.println("恭喜您获得500积分");
		}else{
			System.out.println("对不起您暂不支持兑换");
		}
		
	}

}
`

**Comment by wanghanyangks** [comment]
`package Work0418;

import java.util.Scanner;

public class VipUser {

	public static void main(String[] args) {
		Scanner sc=new Scanner(System.in);
		User u=new User();
		System.out.println("请输入积分");
		u.integral=sc.nextInt();
		System.out.println("请输入卡类型");
		u.cardType=sc.next();
		u.exchange();
		sc.close();

	}

}`

**Comment by yudequan** [comment]
**审核通过，可以提交到git。**
